### ISSUE TITLE
RuntimeError with context manager and no_print=True

### ISSUE THREAD

**Issue by ahalterman** [ines/wasabi#2]
First of all, thanks for `wasabi`! It's really easy to use and most importantly, looks cool.

I just ran into an error using the context manager and `no_print=True`. I have a `verbose` option in my code that I'd like to use to control whether `wasabi` prints loading messages, but I've encountered an error. If I change the context manager example in the docs from `msg = Printer()` to `msg = Printer(no_print=True)`, I get a RuntimeError. Full code, output, and error below:

```
from wasabi import Printer
import time

msg = Printer(no_print=True)
with msg.loading("Loading..."):
    # Do something here that takes longer
    time.sleep(5)
msg.good("Successfully loaded something!")
```
Nothing for 5 seconds, then the following:
```
⠙ Loading...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-455695c9f881> in <module>()
      1 with msg.loading("Loading..."):
      2     # Do something here that takes longer
----> 3     time.sleep(5)
      4 msg.good("Successfully loaded something!")

~/anaconda3/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     90                 return False
     91             else:
---> 92                 raise RuntimeError("generator didn't stop")
     93         else:
     94             if value is None:

RuntimeError: generator didn't stop

⠧ Loading...
```

**Comment by ines** [comment]
Thanks for the report – I just tested it, was able to reproduce it and I think it all came down to an `if` in the loading contextmanager that should have been an `elif` 🤦‍♀️

**Comment by ahalterman** [comment]
That fixed it! Thank you.
