### ISSUE TITLE
Adding custom COLORS values to traceback

### ISSUE THREAD

**Issue by mr-bjerre** [ines/wasabi#4]
Hi @ines 

Lovely tool!

In `Printer` I can provide my own `colors` dictionary but that is not an option in `TracebackPrinter`. The colors being used there are defined by `wasabi.COLORS`. I need to change it since Pycharm only supports certain ANSI colors. Is that possible?

Btw. do you combine wasabi with `logging` module? I was considering adding a `WasabiStreamHandler` but maybe it already exists?

**Comment by ines** [comment]
Thanks! 🙂

> In Printer I can provide my own colors dictionary but that is not an option in TracebackPrinter. 

The `TracebackPrinter` does support customising the `color_error`, `color_tb` and `color_highlight`, though. Those values are directly passed to the [`color` helper](https://github.com/ines/wasabi/blob/2beb8fe98cdfe9cafcae0a7c7b18c9738119e337/wasabi/util.py#L60), so they can be string values from the `COLORS` dict, but also integers of the color values (e.g. `color_error=160`).

> Btw. do you combine wasabi with logging module? I was considering adding a WasabiStreamHandler but maybe it already exists?

No, we haven't really needed that, so I haven't tried it and it's not on my list for a built-in feature at the moment. But you could probably write your own wrapper around it pretty easily. If you set `no_print=True`, the `Printer` will only return the formatted string and not actually call `print()` around it, so you can then pass that to some other process.
